### Regression : Customer Purchase
GET http://localhost:8080/regression

### Regression : Customer Purchase V2
GET http://localhost:8080/regression/v2

### Sentiment : Product Review
GET http://localhost:8080/sentiment

### Sentiment : Product Review V2
GET http://localhost:8080/sentiment/v2

### Image Recognition : Native Java
GET http://localhost:8080/image-recognition

### Image Recognition : DJL4J PyTorch
GET http://localhost:8080/image-recognition/v2

### Image Recognition : DJL4J PyTorch with Path Variable
### book.png, coffee_mug.jpg, laptop.jpg, pill_bottle.png, smartphone.png
GET http://localhost:8080/image-recognition/v3/smartphone.png
