spring:
  application:
    name: Latihan Java 21 Spring AI

springdoc:
  packages-to-scan: id.latihan.java21.spring.ai.controller
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  enable-spring-security: true

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: https://generativelanguage.googleapis.com
    model : /v1beta/models/gemini-1.5-flash-latest:generateContent

logging:
  level:
    org:
      springframework:
        web:
          reactive:
            function:
              client: DEBUG