spring:
  application:
    name: Latihan Java 21 Spring AI
  ai:
    openapi:
      api-key: ${OPENAI_API_KEY}
      model: gpt-3.5-turbo
      chat:
        api-key: ${OPENAI_API_KEY}

springdoc:
  packages-to-scan: id.latihan.java21.spring.ai.controller
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  enable-spring-security: true

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: https://generativelanguage.googleapis.com
    model : /v1beta/models/gemini-1.5-flash-latest:generateContent

openai:
  api:
    key: ${OPENAI_API_KEY}
#    url: https://api.openai.com/v1/chat/completions
    url: https://api.openai.com/v1/responses

logging:
  level:
    org:
      springframework:
        web:
          reactive:
            function:
              client: DEBUG
        ai: DEBUG